config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :categories
    resources :products
    resources :orders, only: [:show, :index, :update, :destroy]
    resources :users, only: [:index, :destroy]
    root 'dashboard#index'
  end

  resources :categories, :only => [:show]

  delete 'cart/remove_product/:product_id' => 'carts#remove_product'

  post '/cart/add' => 'carts#add'

  get '/cart' => 'carts#show'

  get '/contact' => 'home#contact'

  get '/my_account' => 'my_account#index'

  get '/my_account/change_password' => 'my_account#change_password'

  get '/my_orders' => 'my_account#my_orders'

  get '/checkout/init' => 'checkout#index'

  post '/checkout/request_token' => 'checkout#request_authy_token'

  post '/checkout/process_order' => 'checkout#process_order'

  get '/myorders' => 'my_orders#index'

  get '/myorders/:id' => 'my_orders#show'

  get '/search' => 'home#search'

  resources :products, :only => [:show]

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_products

  def get_status
    order_products.any? { |product| product.status.downcase == 'pending' } ? 'pending' : 'completed'
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  skip_before_filter :verify_authenticity_token, :only => [:update]
  before_action :set_order, only: [:show, :edit, :destroy]

  # GET /admin/orders
  # GET /admin/orders.json
  def index
    @orders = Order.all
  end

  # GET /admin/orders/1
  # GET /admin/orders/1.json
  def show
  end

  # PATCH/PUT /admin/orders/1
  # PATCH/PUT /admin/orders/1.json
  def update
    @order_product = OrderProduct.find(params[:id])

    respond_to do |format|
      if @order_product.update_attribute(:status, order_params[:status])
        format.html { redirect_to admin_orders_url, notice: 'Order product was successfully updated.' }
      else
        format.html { render :show }
      end
    end
  end

  # DELETE /admin/categories/1
  # DELETE /admin/categories/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order_product).permit(:status)
  end
end

app/views/admin/orders/index.html.erb
<div class="row">
  <p id="notice"><%= notice %></p>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Order Date</th>
        <th>Status</th>
        <th>Total Amount</th>
        <th>No of Products</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <th scope="row">
            <%= link_to "Order# #{order.id}", admin_order_path(order) %>
          </th>
          <td><%= order.order_date.strftime('%d-%m-%Y') %></td>
          <td><%= order.get_status %></td>
          <td><%= format_price(order.total) %></td>
          <td><%= order.product_count %></td>
          <td>
            <%= link_to 'Edit', admin_order_path(order) %> /
            <%= link_to 'Destroy', admin_order_path(order), method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/orders/show.html.erb
<div class="row">
  <table class="table table-striped">
    <thead>
      <tr>
        <th colspan="3">Order# <%= @order.id %></th>
        <th><%= format_price(@order.total) %></th>
      </tr>
      <tr>
        <th>Product</th>
        <th>Price</th>
        <th>Qty</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% @order.order_products.each do |product| %>
        <tr>
          <th scope="row">
            <%= link_to product.product.title, product_path(product.product) %>
          </th>
          <td><%= format_price(product.price) %></td>
          <td><%= product.qty %></td>
          <td>
            <%= form_for(product, url: admin_order_path(product)) do |f| %>
              <%= f.collection_select :status, ['completed', 'pending'],
                :to_s, :to_s, {}, { class: 'custom-select' } %>
              <%= f.submit 'update' %>
            <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>