config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :categories
    resources :products
    resources :orders, only: [:show, :index, :update, :destroy]
    resources :users, only: [:index, :destroy]
    root 'dashboard#index'
  end

  resources :categories, :only => [:show]

  delete 'cart/remove_product/:product_id' => 'carts#remove_product'

  post '/cart/add' => 'carts#add'

  get '/cart' => 'carts#show'

  get '/contact' => 'home#contact'

  get '/my_account' => 'my_account#index'

  get '/my_account/change_password' => 'my_account#change_password'

  get '/my_orders' => 'my_account#my_orders'

  get '/checkout/init' => 'checkout#index'

  post '/checkout/request_token' => 'checkout#request_authy_token'

  post '/checkout/process_order' => 'checkout#process_order'

  get '/myorders' => 'my_orders#index'

  get '/myorders/:id' => 'my_orders#show'

  get '/search' => 'home#search'

  resources :products, :only => [:show]

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/controllers/my_account_controller.rb
class MyAccountController < ApplicationController
  layout :set_layout

  # GET my account page
  def index; end

  # GET user password change form
  def change_password; end

  private
  def set_layout
    current_user.present? && current_user.admin_role ? 'admin' : 'application'
  end
end

app/views/my_account/change_password.html.erb
<div class="row">
  <%= render partial: 'common/my_account_sidebar' %>
  <div class="col-md-6 col-lg-6">
    <div class="row">
      <%= form_for(current_user, as: current_user, url: password_path(current_user), html: { method: :put }) do |f| %>
        <%= f.hidden_field :reset_password_token %>

        <div class="form-group">
          <%= f.label :password, "New password" %><br />
          <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em><br />
          <% end %>
          <%= f.password_field :password, autofocus: true, autocomplete: "off", class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation, "Confirm new password" %><br />
          <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.submit "Change password", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/my_account/index.html.erb
<div class="row">

  <%= render partial: 'common/my_account_sidebar' %>

  <div class="col-md-9">
    <div class="row">
    </div>
  </div>

</div>