config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :categories
    resources :products
    resources :orders, only: [:show, :index, :update, :destroy]
    resources :users, only: [:index, :destroy]
    root 'dashboard#index'
  end

  resources :categories, :only => [:show]

  delete 'cart/remove_product/:product_id' => 'carts#remove_product'

  post '/cart/add' => 'carts#add'

  get '/cart' => 'carts#show'

  get '/contact' => 'home#contact'

  get '/my_account' => 'my_account#index'

  get '/my_account/change_password' => 'my_account#change_password'

  get '/my_orders' => 'my_account#my_orders'

  get '/checkout/init' => 'checkout#index'

  post '/checkout/request_token' => 'checkout#request_authy_token'

  post '/checkout/process_order' => 'checkout#process_order'

  get '/myorders' => 'my_orders#index'

  get '/myorders/:id' => 'my_orders#show'

  get '/search' => 'home#search'

  resources :products, :only => [:show]

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category, required: false

  before_validation { image.clear if @delete_image }

  before_validation { product_file.clear if @delete_product_file }

  has_attached_file :image, styles: { medium: "220x331>", thumb: "142x215>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  has_attached_file :product_file
  validates_attachment_content_type :product_file, :content_type => ['application/pdf', 'application/msword', 'text/plain']

  validates :product_file, attachment_presence: true

  validates :title, presence: true, uniqueness: true

  validates :price, presence: true, numericality: true

  before_destroy :delete_attachments

  searchable do
    text :title
    integer :price
    integer :category_id
    integer :sell_counter
  end

  def delete_image
    @delete_image ||= false
  end

  def delete_image=(value)
    @delete_image  = !value.to_i.zero?
  end

  def delete_product_file
    @delete_product_file ||= false
  end

  def delete_product_file=(value)
    @delete_product_file  = !value.to_i.zero?
  end

  def delete_attachments
    if self.product_file.present? && self.product_file.path.present?
      product_path = self.product_file.path
      File.delete(product_path)  && File.exist?(product_path)
    end
    if self.image.present? && self.image.path.present?
      image_file = self.image.path
      File.delete(image_file) if image_file.present? && File.exist?(image_file)
    end
  end
end

app/models/product_type.rb
class ProductType < ApplicationRecord
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :set_admin_product, only: [:show, :edit, :update, :destroy]

  # GET /admin/products
  # GET /admin/products.json
  def index
    @products = Product.all
  end

  # GET /admin/products/1
  # GET /admin/products/1.json
  def show
  end

  # GET /admin/products/new
  def new
    @product = Product.new
  end

  # GET /admin/products/1/edit
  def edit
  end

  # POST /admin/products
  # POST /admin/products.json
  def create
    @product = Product.new(product_params)
    @product.price = @product.price.to_f.round(2)
    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_products_url, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/1
  # PATCH/PUT /admin/products/1.json
  def update
    respond_to do |format|
      product_value_params = product_params
      product_value_params[:out_of_stock] = product_value_params[:out_of_stock].to_i
      product_value_params[:price] = product_value_params[:price].to_f.round(2) if product_value_params[:price].present?

      if @product.update(product_value_params)
        format.html { redirect_to admin_products_url, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1
  # DELETE /admin/products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :product_type_id, :no_of_pages, :publisher, :publication_date, :isbn, :price, :writer_name, :image, :product_file, :category_id, :out_of_stock,)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_categories

  # GET show a product
  def show
    @product = Product.find(params[:id])
  end

end

app/views/admin/products/_form.html.erb
<% if product.errors.any? %>
  <div id="error_explanation" class="text-danger">
    <h4><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h4>
    <ul class="list-group">
    <% product.errors.full_messages.each do |message| %>
      <li class="list-group-item"><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control', placeholder: 'Enter title' %>
  <small id="titleHelp" class="form-text text-muted">Title of your product</small>
</div>

<div class="form-group">
  <%= f.label :category_id %>
  <%= f.collection_select :category_id, Category.order(:name), :id, :name, {}, { class: 'form-control' } %>
</div>

<div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :product_type_id %>
  <%= f.collection_select :product_type_id, ProductType.order(:name), :id, :name, {}, {class: 'form-control'} %>
</div>

<div class="form-group">
  <%= f.label :no_of_pages %>
  <%= f.number_field :no_of_pages, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :publisher %>
  <%= f.text_field :publisher, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :isbn %>
  <%= f.text_field :isbn, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :price %>
  <%= f.text_field :price, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :writer_name %>
  <%= f.text_field :writer_name, class: 'form-control' %>
</div>

<div class="form-group">
  <div class="form-check">
    <label class="form-check-label">
      <%= f.check_box :out_of_stock, class: 'form-check-input' %>
      Out of Stock
    </label>
  </div>
</div>

<div class="form-group">
  <%= f.label :image %>
  <% if @product.image.exists? %>
    <%= image_tag(@product.image.url(:thumb), class: 'thumbnail_image img-thumbnail') %><br/><br/>
  <% end %>
  <%= f.file_field :image, class: 'form-control' %>
  <small id="fileHelp" class="form-text text-muted">
    Image file(only jpeg, jpg, png)
  </small>
  <div class="form-check">
    <label class="form-check-label">
      <%= f.check_box :delete_image, class: 'form-check-input' %>
      Delete Image
    </label>
  </div>
</div>

<div class="form-group">
  <%= f.label :product_file %>
  <% if @product.product_file.exists? %>
    <a href="<%= @product.product_file.url %>" target="_blank">Download File</a><br/>
  <% end %>
  <%= f.file_field :product_file, class: 'form-control' %>
  <small id="fileHelp" class="form-text text-muted">
    Product file(only pdf)
  </small>
  <div class="form-check">
    <label class="form-check-label">
      <%= f.check_box :delete_product_file, class: 'form-check-input' %>
      Delete Product File
    </label>
  </div>
</div>

<div class="form-group">
  <%= f.submit 'Submit', class: 'btn btn-primary' %>
  <%= link_to 'Back', admin_products_path, class: 'btn btn-warning btn-sm' %>
</div>

app/views/admin/products/edit.html.erb
<div class="col-8 col-sm-8">
  <h3>Edit Product</h3>
  <%= form_for(@product, url: admin_product_path(@product)) do |f| %>
    <%= render 'form', product: @product, f: f %>
  <% end %>
</div>

app/views/admin/products/index.html.erb
<p id="notice"><%= notice %></p>
<h3>Products</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>No pages</th>
      <th>Publisher</th>
      <th>Price</th>
      <th>Out of Stock</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |admin_product| %>
      <tr>
        <td scope="row"><%= admin_product.title %></td>
        <td><%= admin_product.no_of_pages %></td>
        <td><%= admin_product.publisher %></td>
        <td><%= format_price(admin_product.price) %></td>
        <td class="text-center">
          <% if admin_product.out_of_stock %>
            <span class="text-danger">Out of Stock</span>
          <% else %>
            <span class="text-success">In Stock</span>
          <% end %>
        </td>
        <td><%= link_to 'Edit', edit_admin_product_path(admin_product) %></td>
        <td><%= link_to 'Destroy', admin_product_path(admin_product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Product', new_admin_product_path, class: 'btn btn-primary btn-sm' %>

app/views/admin/products/new.html.erb
<div class="col-8 col-sm-8">
  <h3>New Product</h3>
  <%= form_for(@product, url: admin_products_path, html: { multipart: true }) do |f| %>
    <%= render 'form', product: @product, f: f %>
  <% end %>
</div>